databases:
  - name: tm
    databaseName: tm
    user: tm
    region: singapore

services:
  - type: web
    name: tm
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tm
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
